
import {Poppins, Open_Sans, Roboto, Ubuntu} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";
import NavbarWrapper from "@/context/NavbarWrapper";
import Footer from "@/components/Footer/Footer";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const ubutntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});


export const metadata = {
  title: "Jonosokti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body suppressHydrationWarning={true} className={poppins.className}>
        <div>
          {/* <Navbar /> */}
          <NavbarWrapper/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
