import React from "react";
import Link from "next/link";

const page = () => {
  return (
    <section className="pt-24 pb-10 animate-fadeIn max-w-5xl mx-auto">
      <div className="container mx-auto px-2 md:px-0">
        {/* Page Title */}
        <h2 className="text-center text-xs md:text-sm my-5 capitalize">
          <Link href="/">home</Link> / Privacy Policy
        </h2>

        <div>
          {/* introduction  */}
          <div className="space-y-4 ">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              1. Introduction
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Welcome to <span>Jonosokti Private Ltd.</span>
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Jonosokti Ltd. (“us”, “we”, or “our”) operates jonosokti.com
              (hereinafter referred to as “Service”).
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Our Privacy Policy governs your visit to
              <Link className="underline" href={"https://jonosokti.com"} target="_blank">
                jonosokti.com
              </Link>
              , and explains how we collect, safeguard and disclose information
              that results from your use of our Service
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We use your data to provide and improve Service. By using Service,
              you agree to the collection and use of information in accordance
              with this policy. Unless otherwise defined in this Privacy Policy,
              the terms used in this Privacy Policy have the same meanings as in
              our Terms and Conditions.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Our Terms and Conditions (“Terms”) govern all use of our Service
              and together with the Privacy Policy constitutes your agreement
              with us (“agreement”).
            </p>
          </div>

          {/* Definitions  */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              2. Definitions
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold">SERVICE</span> means the Jonosokti.com
              website operated by Jonosokti Ltd..
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold">PERSONAL DATA</span> means data about
              a living individual who can be identified from those data (or from
              those and other information either in our possession or likely to
              come into our possession).
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold">USAGE DATA</span> is data collected
              automatically either generated by the use of Service or from
              Service infrastructure itself (for example, the duration of a page
              visit).
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold">COOKIES</span> are small files stored
              on your device (computer or mobile device).
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold">DATA CONTROLLER</span> means a natural
              or legal person who (either alone or jointly or in common with
              other persons) determines the purposes for which and the manner in
              which any personal data are, or are to be, processed. For the
              purpose of this Privacy Policy, we are a Data Controller of your
              data.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold">
                DATA PROCESSORS (OR SERVICE PROVIDERS)
              </span>{" "}
              means any natural or legal person who processes the data on behalf
              of the Data Controller. We may use the services of various Service
              Providers in order to process your data more effectively.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold"> DATA SUBJECT</span> is any living
              individual who is the subject of Personal Data.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              <span className="font-bold">THE USER</span> is the individual
              using our Service. The User corresponds to the Data Subject, who
              is the subject of Personal Data.
            </p>
          </div>

          {/* Information Collection and Use  */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              3. Information Collection and Use
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </p>
          </div>

          {/* Types of Data Collected  */}
          <div className="space-y-4 ">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              4. Types of Data Collected
            </h2>
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              Personal Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (“Personal Data”). Personally identifiable
              information may include, but is not limited to:
            </p>

            <ul>
              <li>0.1. Email address</li>
              <li>0.2. First name and last name</li>
              <li>0.3. Phone number</li>
              <li>
                0.4. Address, Country, State, Province, ZIP/Postal code, City
              </li>
              <li>0.5. Voter ID</li>
              <li>0.6. Pictures</li>
              <li>0.7. Company address</li>
              <li>0.8. Cookies and Usage Data</li>
            </ul>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us by following the unsubscribe link.
            </p>

            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              Usage Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may also collect information that your browser sends whenever
              you visit our Service or when you access Service by or through any
              device (“Usage Data”).
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              This Usage Data may include information such as your computer’s
              Internet Protocol address (e.g. IP address), browser type, browser
              version, the pages of our Service that you visit, the time and
              date of your visit, the time spent on those pages, unique device
              identifiers and other diagnostic data.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              When you access Service with a device, this Usage Data may include
              information such as the type of device you use, your device unique
              ID, the IP address of your device, your device operating system,
              the type of Internet browser you use, unique device identifiers
              and other diagnostic data.
            </p>

            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              Location Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may use and store information about your location if you give
              us permission to do so (“Location Data”). We use this data to
              provide features of our Service, to improve and customize our
              Service.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              You can enable or disable location services when you use our
              Service at any time by way of your device settings.
            </p>

            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              Tracking Cookies Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We use cookies and similar tracking technologies to track the
              activity on our Service and we hold certain information.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Cookies are files with a small amount of data which may include an
              anonymous unique identifier. Cookies are sent to your browser from
              a website and stored on your device. Other tracking technologies
              are also used such as beacons, tags and scripts to collect and
              track information and to improve and analyze our Service.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Examples of Cookies we use:
            </p>
            <div>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.1. Session Cookies: We use Session Cookies to operate our
                Service.
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.2. Preference Cookies: We use Preference Cookies to remember
                your preferences and various settings.
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3. Security Cookies: We use Security Cookies for security
                purposes.
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.4. Advertising Cookies: Advertising Cookies are used to serve
                you with advertisements that may be relevant to you and your
                interests.
              </p>
            </div>
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              Other Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              While using our Service, we may also collect the following
              information: sex, age, date of birth, place of birth, passport
              details, citizenship, registration at place of residence and
              actual address, telephone number (work, mobile), details of
              documents on education, qualification, professional training,
              employment agreements, NDA agreements, information on bonuses and
              compensation, information on marital status, family members,
              social security (or other taxpayer identification) number, office
              location and other data.
            </p>
          </div>

          {/* Use of Data  */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              5. Use of Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Jonosokti Ltd. uses the collected data for various purposes:
            </p>

            <div>
              <p className="text-sm md:text-textmedium text-textColor">
                0.1. to provide and maintain our Service;
              </p>
              <p className="text-sm md:text-textmedium text-textColor">
                0.2. to notify you about changes to our Service;
              </p>
              <p className="text-sm md:text-textmedium text-textColor">
                0.3. to allow you to participate in interactive features of our
                Service when you choose to do so;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.4. to provide customer support;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.5. to gather analysis or valuable information so that we can
                improve our Service;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.6. to monitor the usage of our Service;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.7. to detect, prevent and address technical issues
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.8. to fulfil any other purpose for which you provide it;
              </p>
              <p className="leading-6 leading-text-sm md:text-textmedium text-textColor">
                0.9. to carry out our obligations and enforce our rights arising
                from any contracts entered into between you and us, including
                for billing and collection;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.10. to provide you with notices about your account and/or
                subscription, including expiration and renewal notices,
                email-instructions, etc.;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.11. to provide you with news, special offers and general
                information about other goods, services and events which we
                offer that are similar to those that you have already purchased
                or enquired about unless you have opted not to receive such
                information;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.12. in any other way we may describe when you provide the
                information;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.13. for any other purpose with your consent.
              </p>
            </div>
          </div>

          {/* Retention of Data  */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              6. Retention of Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We will retain your Personal Data only for as long as is necessary
              for the purposes set out in this Privacy Policy. We will retain
              and use your Personal Data to the extent necessary to comply with
              our legal obligations (for example, if we are required to retain
              your data to comply with applicable laws), resolve disputes, and
              enforce our legal agreements and policies.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We will also retain Usage Data for internal analysis purposes.
              Usage Data is generally retained for a shorter period, except when
              this data is used to strengthen the security or to improve the
              functionality of our Service, or we are legally obligated to
              retain this data for longer time periods.
            </p>
          </div>

          {/* Transfer of Data  */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              7. Transfer of Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Your information, including Personal Data, may be transferred to –
              and maintained on – computers located outside of your state,
              province, country or other governmental jurisdiction where the
              data protection laws may differ from those of your jurisdiction
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              If you are located outside Bangladesh and choose to provide
              information to us, please note that we transfer the data,
              including Personal Data, to Bangladesh and process it there.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Your consent to this Privacy Policy followed by your submission of
              such information represents your agreement to that transfer.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Jonosokti Ltd. will take all the steps reasonably necessary to
              ensure that your data is treated securely and in accordance with
              this Privacy Policy and no transfer of your Personal Data will
              take place to an organisation or a country unless there are
              adequate controls in place including the security of your data and
              other personal information.
            </p>
          </div>

          {/* Disclosure of Data  */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              8. Disclosure of Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may disclose personal information that we collect, or you
              provide:
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor" />
            0.1. <span>Disclosure for Law Enforcement.</span>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Under certain circumstances, we may be required to disclose your
              Personal Data if required to do so by law or in response to valid
              requests by public authorities.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.2. Business Transaction.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              If we or our subsidiaries are involved in a merger, acquisition or
              asset sale, your Personal Data may be transferred.
            </p>
            <div className="flex items-start gap-2 flex-col">
              <h2>0.3. Other cases. We may disclose your information also:</h2>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3.1. to our subsidiaries and affiliates;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3.2. to contractors, service providers, and other third
                parties we use to support our business;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3.3. to fulfill the purpose for which you provide it;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3.4. for the purpose of including your company’s logo on our
                website;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3.5. for any other purpose disclosed by us when you provide
                the information;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3.6. with your consent in any other cases;
              </p>
              <p className="leading-6 text-sm md:text-textmedium text-textColor">
                0.3.7. if we believe disclosure is necessary or appropriate to
                protect the rights, property, or safety of the Company, our
                customers, or others.
              </p>
            </div>
          </div>

          {/* Security of Data  */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              9. Security of Data
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              The security of your data is important to us but remember that no
              method of transmission over the Internet or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your Personal Data, we cannot
              guarantee its absolute security.
            </p>
          </div>

          {/* Your Data Protection Rights   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              10. Your Data Protection Rights
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              You have certain data protection rights. We aim to take reasonable
              steps to allow you to correct, amend, delete, or limit the use of
              your Personal Data. If you wish to be informed what Personal Data
              we hold about you and if you want it to be removed from our
              systems, please email us at <span>info@jonosokti.com</span>.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              In certain circumstances, you have the following data protection
              rights:
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.1. the right to access, update or to delete the information we
              have on you;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.2. the right of rectification. You have the right to have your
              information rectified if that information is inaccurate or
              incomplete;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.3. the right to object. You have the right to object to our
              processing of your Personal Data;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.4. the right of restriction. You have the right to request that
              we restrict the processing of your personal information;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.5. the right to data portability. You have the right to be
              provided with a copy of your Personal Data in a structured,
              machine-readable and commonly used format;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.6. the right to withdraw consent. You also have the right to
              withdraw your consent at any time where we rely on your consent to
              process your personal information;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Please note that we may ask you to verify your identity before
              responding to such requests. Please note, we may not able to
              provide Service without some necessary data.
            </p>
          </div>

          {/* Your Data Protection Rights    */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              11. Your Data Protection Rights
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Websites collecting personally identifiable information from
              consumers to post a conspicuous privacy policy on its website
              stating exactly the information being collected and those
              individuals with whom it is being shared, and to comply with this
              policy.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We agree to the following:
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.1. users can visit our site anonymously;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.2. our Privacy Policy link includes the word “Privacy”, and can
              easily be found on the home page of our website;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.3. users will be notified of any privacy policy changes on our
              Privacy Policy Page;
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.4. users are able to change their personal information by
              emailing us at info@jonosokti.com.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Our Policy on “Do Not Track” Signals:
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We honor Do Not Track signals and do not track, plant cookies, or
              use advertising when a Do Not Track browser mechanism is in place.
              Do Not Track is a preference you can set in your web browser to
              inform websites that you do not want to be tracked.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              You can enable or disable Do Not Track by visiting the Preferences
              or Settings page of your web browser.
            </p>
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              0.1. What personal information we have about you. If you make this
              request, we will return to you:
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.0.1. The categories of personal information we have collected
              about you.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.0.2. The categories of sources from which we collect your
              personal information.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.0.3. The business or commercial purpose for collecting or
              selling your personal information.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.0.4. The categories of third parties with whom we share personal
              information.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              0.0.5. The specific pieces of personal information we have
              collected about you.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Please note, you are entitled to ask us to provide you with this
              information up to two times in a rolling twelve-month period. When
              you make this request, the information provided may be limited to
              the personal information we collected about you in the previous 12
              months.
            </p>
            <h2 className="text-textHeadingColor font-semibold text-sm leading-6 md:text-base">
              0.2. To delete your personal information. If you make this
              request, we will delete the personal information we hold about you
              as of the date of your request from our records and direct any
              service providers to do the same. In some cases, deletion may be
              accomplished through de-identification of the information. If you
              choose to delete your personal information, you may not be able to
              use certain functions that require your personal information to
              operate.
            </h2>
            <h2 className="text-textHeadingColor font-semibold text-sm leading-6 md:text-base">
              0.3. To stop selling your personal information. We don’t sell or
              rent your personal information to any third parties for any
              purpose. We do not sell your personal information for monetary
              consideration. However, under some circumstances, a transfer of
              personal information to a third party, or within our family of
              companies, without monetary consideration may be considered a
              “sale” under California law. You are the only owner of your
              Personal Data and can request disclosure or deletion at any time.
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              If you submit a request to stop selling your personal information,
              we will stop making such transfers.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Please note, if you ask us to delete or stop selling your data, it
              may impact your experience with us, and you may not be able to
              participate in certain programs or membership services which
              require the usage of your personal information to function. But in
              no circumstances, we will discriminate against you for exercising
              your rights.
            </p>
          </div>

          {/* . Service Providers   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              12. . Service Providers
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may employ third party companies and individuals to facilitate
              our Service (“Service Providers”), provide Service on our behalf,
              perform Service-related services or assist us in analysing how our
              Service is used.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              These third parties have access to your Personal Data only to
              perform these tasks on our behalf and are obligated not to
              disclose or use it for any other purpose.
            </p>
          </div>

          {/* . Analytics   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              12. Analytics
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may use third-party Service Providers to monitor and analyze
              the use of our Service.
            </p>
          </div>

          {/* . CI/CD tools   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              14. CI/CD tools
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may use third-party Service Providers to automate the
              development process of our Service.
            </p>
          </div>

          {/* . Advertising   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              15. Advertising
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may use third-party Service Providers to show advertisements to
              you to help support and maintain our Service.
            </p>
          </div>

          {/* . Behavioral Remarketing   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              16. Behavioral Remarketing
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may use remarketing services to advertise on third party
              websites to you after you visited our Service. We and our
              third-party vendors use cookies to inform, optimise and serve ads
              based on your past visits to our Service.
            </p>
          </div>

          {/* . Payments   */}
          <div className="space-y-4 mt-10 ">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              17. Payments
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Primarily service user will pay directly to the service provider
              in cash or other relevant form. We may provide paid products
              and/or services within Service. In that case, we use third-party
              services for payment processing (e.g. payment processors).
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We will not store or collect your payment card details. That
              information is provided directly to our third-party payment
              processors whose use of your personal information is governed by
              their Privacy Policy.{" "}
            </p>
          </div>

          {/* . Links to Other Sites   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              18. Links to Other Sites
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Our Service may contain links to other sites that are not operated
              by us. If you click a third party link, you will be directed to
              that third party’s site. We strongly advise you to review the
              Privacy Policy of every site you visit.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              {" "}
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>
          </div>

          {/* . Children’s Privacy   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              19. Children’s Privacy
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              Our Services are not intended for use by children under the age of
              18 (“Child” or “Children”).
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              {" "}
              We do not knowingly collect personally identifiable information
              from Children under 18. If you become aware that a Child has
              provided us with Personal Data, please contact us. If we become
              aware that we have collected Personal Data from Children without
              verification of parental consent, we take steps to remove that
              information from our servers.
            </p>
          </div>

          {/* . Changes to This Privacy Policy   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              20. Changes to This Privacy Policy
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              We may update our Privacy Policy from time to time. We will notify
              you of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              {" "}
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </div>

          {/* . Contact Us   */}
          <div className="space-y-4 mt-10">
            <h2 className="text-textHeadingColor font-bold text-base md:text-lg">
              21. Contact Us
            </h2>
            <p className="leading-6 text-sm md:text-textmedium text-textColor">
              If you have any questions about this Privacy Policy, please
              contact us by email: <span className="font-semibold">info@jonosokti.com</span>.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default page;
