name: Deploy Frontend

on:
  push:
    branches: 
      - main
    paths:
      - 'frontend/**'  # Only trigger when frontend/ files change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP}}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/nextjs/Jonosokti/frontend
            git pull origin main
            npm install
            npm run build
            pm2 restart "jonosokti-client"
