name: Deploy Frontend
on:
  push:
    paths:
      - 'frontend/**'  # Only trigger when frontend/ files change
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SECRETS_VPS_IP }}
          username: ${{ secrets.SECRETS_VPS_USERNAME }}
          key: ${{ secrets.SECRETS_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/nextjs/Jonosokti/frontend
            git pull origin main
            npm install
            npm run build
            pm2 restart "jonosokti-client"